apiVersion: v1
kind: ConfigMap
metadata:
  name: child-service-config
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://mysql:3306/child_db
    spring.datasource.username=root
    spring.datasource.password=root
    spring.jpa.hibernate.ddl-auto=none
    spring.cloud.config.uri=http://config-server:8888
