apiVersion: v1
kind: Service
metadata:
  name: child-service
  labels:
    app: child-service
spec:
  selector:
    app: child-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
